---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-ml-cpp
  description: Buildkite Pipeline for ml-cpp
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/ml-cpp

spec:
  type: buildkite-pipeline
  owner: group:ml-core
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: ml-cpp
    spec:
      repository: elastic/ml-cpp
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        # your-team:
        #  access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
