## 🏠/.buildkite/pipeline.yml

steps:
  - label: "Validate formatting with clang-format"
    command: ".buildkite/scripts/steps/check-style.sh"
    agents:
      image: "docker.elastic.co/ml-dev/ml-check-style:2.bk"
