## 🏠/.buildkite/pipeline.yml
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License
# 2.0 and the following additional limitation. Functionality enabled by the
# files subject to the Elastic License 2.0 may only be used in production when
# invoked by an Elasticsearch process with a license key installed that permits
# use of machine learning features. You may not use this file except in
# compliance with the Elastic License 2.0 and the foregoing additional
# limitation.
env:
  BUILDKITE_REPO: "https://github.com/elastic/ml-cpp.git"
  BUILD_OS: "linux"
  BUILD_ARCH: "x86_64"
  BUILD_TYPE: "RelWithDebInfo"
  BUILD_SNAPSHOT: "yes"
  CMAKE_FLAGS: "-DCMAKE_TOOLCHAIN_FILE=cmake/linux-x86_64.cmake"
steps:
  #- label: "Validate formatting with clang-format"
  #  key: "check_style"
  #  command: ".buildkite/scripts/steps/check-style.sh --all"
  #  agents:
  #    image: "docker.elastic.co/ml-dev/ml-check-style:2"
  #- label: "Build & test :cpp: for linux-x86_64-RelWithDebInfo"
  #  timeout_in_minutes: 180
  #  agents:
  #    cpu: "6"
  #    ephemeralStorage: "20G"
  #    #machineType: "c2-highcpu-32"
  #    memory: "64G"
  #    image: "docker.elastic.co/ml-dev/ml-linux-build:24"
  #  commands:
  #    - "echo nproc = $(nproc)"
  #    - "cat /proc/cpuinfo"
  #    - "cat /proc/meminfo"
  #    - ".buildkite/scripts/steps/build_and_test.sh"
  #  depends_on: "check_style"
  #  # If changing the key here you will also need to
  #  # update the reference in hooks/post-checkout
  #  key: "build_test_linux-x86_64-RelWithDebInfo"
  #  plugins:
  #    - test-collector#v1.2.0:
  #        files: "lib/*/unittest/boost_test_results.junit"
  #        format: "junit"
  #  env:
  #    RUN_TESTS: "true"
  #    BOOST_TEST_OUTPUT_FORMAT_FLAGS: "--logger=JUNIT,error,boost_test_results.junit"
  - label: "Java Integration Tests"
    key: "java_integration_tests"
    command: 
      - 'buildkite-agent artifact download "build/*" . --build 01850b10-7004-48ec-b445-7d72d47614b6'
      - "mkdir -p ${HOME}/.ssh"
      - "ssh-keyscan github.com >> ~/.ssh/known_hosts"
      - ".buildkite/scripts/steps/run_es_tests.sh"
        #depends_on: "build_test_linux-x86_64-RelWithDebInfo"
    agents:
      image: "gradle:7.2.0-jdk17"
    env:
      IVY_REPO: "${REPO_ROOT}/../ivy"
