#!/bin/bash
#
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License;
# you may not use this file except in compliance with the Elastic License.
#

# The non-Windows part of ML C++ CI:
#
# 1. Build and unit test the Linux version of the C++
# 2. Build the macOS version of the C++
# 3. Upload the builds to the artifacts directory on S3 that
#    subsequent Java builds will download the C++ components from
#
# The builds run in Docker containers that ensure OS dependencies
# are appropriate given the support matrix.
#
# The macOS build cannot be unit tested as it is cross-compiled.

set -e

# Change directory to the directory containing this script
cd `dirname $0`

# Default to a snapshot build
if [ -z "$SNAPSHOT" ] ; then
    SNAPSHOT=yes
fi

# Remove any old builds
rm -rf ../builds

# Build and test Linux
./docker_test.sh linux

# Build macOS
./docker_build.sh macosx

# Upload
cd ..
./gradlew --info -b upload.gradle upload

