#
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License;
# you may not use this file except in compliance with the Elastic License.
#

include $(CPP_SRC_HOME)/mk/defines.mk

.PHONY: test
.PHONY: memcheck
.PHONY: build
.PHONY: install

COMPONENTS= \
            core \
            ver \
            maths \
            model \
            api \
            config \
            seccomp \
            test \



include $(CPP_SRC_HOME)/mk/toplevel.mk

