#!/bin/bash
# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
# or more contributor license agreements. Licensed under the Elastic License
# 2.0 and the following additional limitation. Functionality enabled by the
# files subject to the Elastic License 2.0 may only be used in production when
# invoked by an Elasticsearch process with a license key installed that permits
# use of machine learning features. You may not use this file except in
# compliance with the Elastic License 2.0 and the foregoing additional
# limitation.

set -euo pipefail

export BUILDKITE_ANALYTICS_TOKEN="8uQPFPS8KQPFP3xJXVWfR5Wu"

if [ "$BUILDKITE_PIPELINE_SLUG" = "ml-cpp" && "$BUILDKITE_STEP_KEY" = "linux-x86_64-RelWithDebInfo" ]; then
  export BUILDKITE_ANALYTICS_TOKEN="8uQPFPS8KQPFP3xJXVWfR5Wu"
  export CONDITIONAL_VARIABLE="true"
fi


