// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
// :issue: https://github.com/elastic/elasticsearch/issues/
// :pull: https://github.com/elastic/elasticsearch/pull/

= Elasticsearch Release Notes

== Elasticsearch version 6.4.0

=== Breaking Changes

=== Deprecations

=== New Features

Detectors now support rules that allow the user to improve the results by providing some domain specific
knowledge in the form of rule. ({pull}119[#119])

=== Enhancements

Improve and use periodic boundary condition for seasonal component modeling ({pull}84[#84])
Improve robustness w.r.t. outliers of detection and initialisation of seasonal components ({pull}90[#90])
Improve behavior when there are abrupt changes in the seasonal components present in a time series ({pull}91[#91])
Explicit change point detection and modelling ({pull}92[#92])
Improve partition analysis memory usage ({pull}97[#97])
Reduce model memory by storing state for periodicity testing in a compressed format ({pull}100[#100])
Improve the accuracy of model memory control ({pull}122[#122])

Forecasting of Machine Learning job time series is now supported for large jobs by temporarily storing
model state on disk ({pull}89[#89])

Secure the ML processes by preventing system calls such as fork and exec. The Linux implemenation uses
Seccomp BPF to intercept system calls and is available in kernels since 3.5. On Windows Job Objects prevent
new processes being created and macOS uses the sandbox functionality ({pull}98[#98])

Fix a bug causing us to under estimate the memory used by shared pointers and reduce the memory consumed
by unnecessary reference counting ({pull}108[#108])

=== Bug Fixes

Age seasonal components in proportion to the fraction of values with which they're updated ({pull}88[#88])
Persist and restore was missing some of the trend model state ({pull}#99[#99])
Stop zero variance data generating a log error in the forecast confidence interval calculation ({pull}#107[#107])

=== Regressions

=== Known Issues

== Elasticsearch version 6.3.0

=== New Features

=== Enhancements

=== Bug Fixes

Function description for population lat_long results should be lat_long instead of mean ({pull}81[#81])

By-fields should respect model_plot_config.terms ({pull}86[#86])

=== Regressions

=== Known Issues
