// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
// :issue: https://github.com/elastic/elasticsearch/issues/
// :pull: https://github.com/elastic/elasticsearch/pull/

= Elasticsearch Release Notes

== Elasticsearch version 6.4.0

=== Breaking Changes

=== Deprecations

=== New Features 

=== Enhancements

Improve and use periodic boundary condition for seasonal component modeling ({pull}84[#84])
Improve robustness w.r.t. outliers of detection and initialisation of seasonal components ({pull}90[#90])
Explicit change point detection and modelling ({pull}92[#92])

Forecasting of Machine Learning job time series is now supported for large jobs by temporarily storing
model state on disk ({pull}89[#89])

=== Bug Fixes

Age seasonal components in proportion to the fraction of values with which they're updated ({pull}88[#88])

=== Regressions

=== Known Issues

== Elasticsearch version 6.3.0

=== New Features

=== Enhancements

=== Bug Fixes

Function description for population lat_long results should be lat_long instead of mean ({pull}81[#81])

By-fields should respect model_plot_config.terms ({pull}86[#86])

=== Regressions

=== Known Issues
