// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
//:issue:           https://github.com/elastic/elasticsearch/issues/
//:ml-issue:        https://github.com/elastic/ml-cpp/issues/
//:pull:            https://github.com/elastic/elasticsearch/pull/
//:ml-pull:         https://github.com/elastic/ml-cpp/pull/

= Elasticsearch Release Notes

////
// To add a release, copy and paste the following text,  uncomment the relevant
// sections, and add a link to the new section in the list of releases at the
// top of the page. Note that release subheads must be floated and sections
// cannot be empty.
// TEMPLATE:

// == {es} version n.n.n

//=== Breaking Changes

//=== Deprecations

//=== New Features

//=== Enhancements

//=== Bug Fixes

//=== Regressions

 == {es} version 6.6.2

=== Bug Fixes

* Fixes an issue where interim results would be calculated after advancing time into an empty bucket. {ml-pull}416[#416]

== {es} version 6.6.0

=== Breaking Changes

=== Deprecations

=== New Features

=== Enhancements

=== Bug Fixes

Fix cause of "Sample out of bounds" error message. {ml-pull}335[#335]

Fix hang when closing a job or creating a forecast. This problem occurs
if you created a forecast for a large job and temporary storage was not cleaned up. {ml-pull}352[#352] (issue: {ml-issue}350[#350])

=== Regressions

== {es} version 6.5.5


== {es} version 6.5.4

None

== {es} version 6.5.3

=== Bug Fixes

Correct query times for model plot and forecast in the bucket to match the times we assign
the samples we add to the model for each bucket. For long bucket lengths, this could result
in apparently shifted model plot with respect to the data and increased errors in forecasts. 

 == {es} version 6.5.0

//=== Breaking Changes

//=== Deprecations

//=== New Features

=== Enhancements

Perform anomaly detection on features derived from multiple bucket values to improve robustness
of detection with respect to misconfigured bucket lengths and improve detection of long lasting
anomalies. (See {ml-pull}175[#175].)

Support decomposing a time series into a piecewise linear trend and with piecewise constant
scaling of the periodic components. This extends our decomposition functionality to handle the
same types of change points that our modelling capabilities do. (See {ml-pull}198[198].)

Increased independence of anomaly scores across partitions (See {ml-pull}182[182].)

Avoid potential false positives at model start up when first detecting new components of the time
series decomposition. (See {ml-pull}218[218].)

Add a new label - multi_bucket_impact - to record level anomaly results.
The value will be on a scale of -5 to +5 where -5 means the anomaly is purely single bucket
and +5 means the anomaly is purely multi bucket. ({ml-pull}230[230])

Improve our ability to detect change points in the presence of outliers. (See {ml-pull}265[265].)

=== Bug Fixes

Fix cause of "Bad density value..." log errors whilst forecasting. ({ml-pull}207[207])

Fix incorrectly missing influencers when the influence field is one of the detector's partitioning
fields and the bucket is empty. ({pull}219[#219])

Fix cause of hard_limit memory error for jobs with bucket span greater than one day. ({ml-pull}243[243])

Fix cause of "Failed to compute significance..." log errors ({ml-pull}272[272])"

Prevent detecting a trend component during a possible change in the time series. The resulting
model was poorly reinitialised in this case which damaged anomaly detection for some time. (See
{ml-pull}287[#287].)

Fix cause of "MERGE: Sum mode samples = 0, total samples = 4.43521.." log errors ({ml-pull}294[294]) 

//=== Regressions

== {es} version 6.4.3

//=== Breaking Changes

//=== Deprecations

//=== New Features

=== Enhancements

* Changes linker options on macOS to allow Homebrew installs ({ml-pull}225[#225])

//=== Bug Fixes

* Fixes the cause of `hard_limit` memory errors for jobs with bucket spans greater 
than one day ({ml-pull}243[#243])
* Rules that trigger the `skip_model_update` action should also apply to the 
anomaly model. This fixes an issue where anomaly scores of results that triggered 
the rule would decrease if they occurred frequently. {ml-pull}222[#222] (issue:{ml-issue}217[#217])

//=== Regressions
