// Use these for links to issue and pulls. Note issues and pulls redirect one to
// each other on Github, so don't worry too much on using the right prefix.
// :issue:    https://github.com/elastic/elasticsearch/issues/
// :pull:     https://github.com/elastic/elasticsearch/pull/
// :ml-issue: https://github.com/elastic/ml-cpp/issues/
// :ml-pull:  https://github.com/elastic/ml-cpp/pull/

= Elasticsearch Release Notes

== Elasticsearch version 6.3.0

=== Breaking Changes

=== Deprecations

=== New Features 

=== Enhancements

* Synchronize long and short tests for periodicity {ml-pull}62[#62]
* Improvements to trend modelling and periodicity testing for forecasting {ml-pull}7[#7] (issue: {ml-issue}5[#5])

=== Bug Fixes

* By-fields should respect model_plot_config.terms {ml-pull}86[#86] (issue: {issue}30004[#30004])
* Function description for population lat_long results should be lat_long instead of mean {ml-pull}81[#81] (issue: {ml-issue}80[#80])
* Fix error causing us to overestimate effective history length {ml-pull}66[#66] (issue: {ml-issue}57[#57])
* Clearing JSON memory allocators {ml-pull}30[#30] (issue: {ml-issue}26[#26])
* Fix sparse data edge cases for periodicity testing {ml-pull}28[#28] (issue: {ml-issue}20[#20])
* Impose an absolute cutoff on the minimum variance {ml-pull}8[#8] (issue: {ml-issue}488[#488])
* Check accesses in bounds when clearing recycled models {ml-pull}79[#79] (issue: {ml-issue}76[#76])
* Set forecast progress to 100% and status finished in the case of insufficient history (data) {ml-pull}44[#44]
* Add control message to start background persistence {ml-pull}19[#19]
* Fail start up if state is missing {ml-pull}4[#4]
* Do not log incorrect model memory limit {ml-pull}3[#3]
* The trend decomposition state wasn't being correctly upgraded potentially causing the autodetect process to abort {ml-pull}136[#136] (issue: {ml-issue}135[#135])
* Fix a SIGSEGV in the autodetect process when jump upgrading from 5.6 to 6.3 {ml-pull}143[#143] (issue: {ml-issue}141[#141]})

=== Regressions

=== Known Issues
